# https://opentdb.com
question_data = [
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Tetris is the #1 best-selling video game of all-time.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                  "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "medium",
                  "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "Bob Ross was a US Air Force pilot.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "Tigers have one colour of skin despite the stripey fur.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
